services:
  bot:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "python", "-m", "delivery_service.bootstrap.entrypoints.bot" ]
    env_file:
      - ".env"

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml