FROM docker.io/library/python:3.12-slim as base

ENV PATH="/venv/bin:$PATH" \
    VIRTUAL_ENV="/venv"

RUN set -eux; apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libpq5 \
    && rm -rf /var/lib/apt/lists/*

# Stage: build
# ---------------------------------------------------------
FROM base as build

ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=0 \
    UV_PROJECT_ENVIRONMENT=/venv

COPY --from=ghcr.io/astral-sh/uv:0.8.13 /uv /uvx /usr/local/bin/

RUN set -eux; apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN uv venv /venv

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

COPY . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv build --wheel && \
    uv pip install --no-deps dist/*.whl

# Stage: final
# ---------------------------------------------------------
FROM base

RUN useradd --system --no-create-home water-user

COPY --from=build /venv /venv
COPY --from=build /app/alembic.ini /app/
COPY --from=build /app/src/backend/infrastructure/persistence/migrations /app/src/backend/infrastructure/persistence/migrations

WORKDIR /app

USER water-user
