name: "Pyright Type Check"
on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.394